apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calunga--runtime-int
namePrefix: calunga-
resources:
  - ../../base
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: quay.io/calungaproject/releases-watcher
    newName: quay.io/calungaproject/releases-watcher
    digest: sha256:c76d0fa99c6f58479682b03b7f2632f137afd511646a8e855b84f340d9920378
